WIP: Add TIR for Infrastructure Components
opendevstack/ods-document-generation-templates pull request #16
Opened 2020-08-07 07:56 UTC by nichtraunzer

2020-08-07 08:00 UTC, nichtraunzer commented
fyi @metmajer

2020-12-09 08:11 UTC, metmajer commented
This branch is outdated and needs to be updated with the changes in `master` once `master` was updated with the changes made in `release/1.1`. FYI @nichtraunzer

2020-12-21 08:47 UTC, martsec requested changes

2020-12-21 08:47 UTC, martsec commented on templates/TIR-infra.html.tmpl
> +        <p>This document describes the installation of the infrastructure component <em>{{metadata.buildParameter.configItem}}</em>. The installation is based on the corresponding Technical Installat
I would remove the word 'infrastructure' from here. 
We can use this quickstarter to deploy application components to the cloud, so this word here is a problem. I am thinking about deploying data pipelines for example. And that is not an infrastructure component. 

FYI @metmajer  @frankjoas  @nichtraunzer

2021-01-31 16:07 UTC, metmajer commented
@nichtraunzer @frankjoas I have integrated these changes into https://github.com/opendevstack/ods-document-generation-templates/pull/26. The latter PR is targeted at branch `release/v1.1`. Once the PR has been merged, we'll merge `release/v1.1` into `master` via a dedicated PR and close this PR. You'll be named as contributors ;-)

2021-01-31 20:41 UTC, metmajer commented
Merged into `release/v1.1` via https://github.com/opendevstack/ods-document-generation-templates/pull/26 and merged into `master` via https://github.com/opendevstack/ods-document-generation-templates/pull/24.

2021-01-31 20:41 UTC, closed without merging