Bugfix/big table content overflow
opendevstack/ods-document-generation-templates pull request #32
Opened 2021-04-13 07:32 UTC by louis-sanchez

Tables are not rendered correctly when the column content is too long.  This fix forces text to wrap and show correctly

2021-04-14 06:28 UTC, metmajer requested changes
@louis-sanchez Due to the exhaustive changes... did you run the templates through an HTML validator? Also, why are indentations not consistent? Templates are supposed to be clean. You'll need a reviewer that verifies for every changed block that the section references have not changed erroneously.

2021-04-14 11:51 UTC, louis-sanchez commented on templates/RA.html.tmpl
> -		<p>{{{data.sections.sec6s1.content}}}</p>
not sure git is indenting this line, but the table that replaces the <p> is indented correctly

2021-04-14 11:53 UTC, louis-sanchez commented on templates/RA.html.tmpl
> -		<p>{{{data.sections.sec6s2.content}}}</p>
not sure git is indenting this line, but the table that replaces the `<p>` is indented correctly

2021-04-14 11:57 UTC, louis-sanchez commented on templates/RA.html.tmpl
> +        <table>
this `<table>` is corrected indented.  the `<p>` was not.

2021-04-14 13:25 UTC, louis-sanchez commented on templates/SSDS-4.html.tmpl
> -			<p>{{{data.sections.sec15.content}}}</p>
incorrect `<p>` formatting

2021-04-14 14:21 UTC, metmajer commented
@louis-sanchez there was a PR merged in the meantime which requires you to create an entry in the Changelog.md. Entries need to follow a certain format. Please look here for examples: https://github.com/opendevstack/ods-jenkins-shared-library/blob/master/CHANGELOG.md

2021-04-14 15:58 UTC, louis-sanchez commented on templates/CFTP-1.html.tmpl
> -		<p>{{{data.sections.sec12.content}}}</p>
`<table>` is now indented correctly.  `<p>` was not.

2021-04-14 15:59 UTC, louis-sanchez commented on templates/CFTP-3.html.tmpl
> -		<p>{{{data.sections.sec12.content}}}</p>
`<table>` is now indented correctly.  `<p>` was not.

2021-04-14 15:59 UTC, louis-sanchez commented on templates/CFTP-4.html.tmpl
> -		<p>{{{data.sections.sec12.content}}}</p>
`<table>` is now indented correctly.  `<p>` was not.

2021-04-14 16:00 UTC, louis-sanchez commented on templates/CFTP-5.html.tmpl
> -		<p>{{{data.sections.sec12.content}}}</p>
`<table>` is now indented correctly.  `<p>` was not.

2021-04-14 18:37 UTC, metmajer commented
@louis-sanchez SSDS templates are still not in shape. Did you do the HTML validation? Please let us know when the review can happen.

2021-04-15 14:09 UTC, s2oBCN approved these changes

2021-04-15 14:20 UTC, merged